[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

# [tool.hatch.build]
# exclude = [
#   "docs*",
#   "tests*",
# ]

[project]
name = "B-HIT"
version = "0.0.1"
description = "A Python package for the identification, characterization and comparison of spatial clusters from spatial -omics data."
readme = "README.md"
requires-python = ">=3.8,<3.13" 
license = {file = "LICENSE"}
authors = [
    {name = "Zeng lab"},
]
# maintainers = [
#     {name = "users", email = "xxxxx@xxxx"},
# ]
# urls.Documentation = "https://cellcharter.readthedocs.io/"
# urls.Source = "https://github.com/CSOgroup/cellcharter"
# urls.Home-page = "https://github.com/CSOgroup/cellcharter"
dependencies = [
    "numpy",
    "pandas",
    "scanpy",
    "scipy",
    "anndata",
    "matplotlib",
    "pytorch",
    "pytorch-lightning >= 1.6.0",
    "torchgmm",
    "scikit-learn",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "pre-commit",       # 帮助开发者避免将不符合代码风格或质量要求的代码提交到代码仓库
    "twine"
]
doc = [
    "docutils>=0.8,!=0.18.*,!=0.19.*",
    "sphinx>=4",
    "sphinx-book-theme>=1.0.0",
    "myst-nb>=1.1.0",
    "sphinxcontrib-bibtex>=1.0.0",
    "sphinx-autodoc-typehints",
    # For notebooks
    "ipykernel",
    "ipython",
    "sphinx-copybutton",
    "sphinx-design"
]
test = [
    "pytest",
    "pytest-cov",
]
transcriptomics = [
    "scvi-tools",
]
proteomics = [
    "scarches",
]

[tool.coverage.run]
source = ["bcell"]
omit = [
    "**/test_*.py",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
xfail_strict = true
addopts = [
    "--import-mode=importlib",  # allow using test files with same name
]
filterwarnings = [
    "ignore::anndata.OldFormatWarning",
    "ignore:.*this fit will run with no optimizer.*",
    "ignore:.*Consider increasing the value of the `num_workers` argument.*",
]

[tool.isort]
include_trailing_comma = true
multi_line_output = 3
profile = "black"
skip_glob = ["docs/*"]

